### ISSUE TITLE
mtgox feed changed

### ISSUE THREAD

**Issue by grant-olson** [JohnMaguire/ichat-mtgox-updater#2]
I was using the original version of the script, and today it complained because the feed changed to https://data.mtgox.com/code/data/ticker.php when before it was https://mtgox.com/code/data/ticker.php

I see you've made some updates, so maybe this is already fixed in the current version.  But I thought I'd let you know.

**Comment by seesolve** [comment]
I have a Mac. Is this still an issue? (I see it's been 2 years…)

**Comment by JohnMaguire** [comment]
If it was an issue then, it's still an issue now. grant suggested it may not have even been an issue then. I'm uninterested in correcting the issue if there is one. Pull requests accepted.

**Comment by JohnMaguire** [comment]
Sorry, I'm a little nervous about this for a couple reasons:

1. I really dislike the binary form that this project is in (and I'm not sure why I didn't pay attention when the pull request came in that switched it that way).
2. Didn't Mt. Gox shutdown? What feed URL did you switch to?

**Comment by JohnMaguire** [comment]
Also, I just checked out your branch and I'm not seeing a difference in feed URLs? "https://data.mtgox.com/code/data/ticker.php" is what was there before...

**Comment by JohnMaguire** [comment]
And in any case -- thank you for trying to contribute. But if Mt. Gox no longer has a feed, I don't think this change is necessary, and I think I'll probably mark this repository as read only.

**Comment by seesolve** [comment]
I do apologize for the binary form. You mentioned not having a Mac. As I understand it, the .scpt format is not readable by non-Mac OS's. Am I wrong about that?

**Comment by seesolve** [comment]
I didn't realize that Mt. Gox no longer had a feed.

**Comment by JohnMaguire** [comment]
The binary form isn't your fault. Two years ago I did not own a Mac. I do now.

**Comment by JohnMaguire** [comment]
No problem. Thanks a lot for trying to resolve this issue! Great to see people helping out in random OSS projects. :)

**Comment by seesolve** [comment]
Oh. Well, then you can make this change yourself. Or, open the main.scpt file yourself. The original main.scpt file showed https://mtgox.com/code/data/ticker.php and I changed it to https://data.mtgox.com/code/data/ticker.php.
